export enum MouthwashRootMessageTag {
    FetchResource = 0x80,
    Resize,
    Intro,
    OverwriteGameOver,
    SetHudString,
    DeclareHat,
    SetGameOption = 0x89,
    DeleteGameOption,
    SetHudVisibility = 0x8c,
    AllowTaskInteraction,
    LoadHat = 0x96,
    LoadPet,
    SetBody,
    LoadSkin,
    ChangeScene,
    MarkAssBrown,
    ModstampSetString,
    SetChatMessage,
    DeleteChatMessage,
    DisplaySystemAnnouncement = 0xfa,
    UpdateDiscordRichPresence,
    SetQrCodeContents
}